export const API_URL = 'https://api.babycycle.my.id/api/v1'
export const API_LOGIN = `${API_URL}/auth/login`
export const API_REGISTER = `${API_URL}/users/register`
export const API_RESEND = `${API_URL}/users/resend_verification`
export const API_VERIFY = `${API_URL}/users/verify`
export const API_ME = `${API_URL}/users/me`
export const API_FORGOT_PASSWORD = `${API_URL}/users/forgot-password`
export const API_RESET_PASSWORD = `${API_URL}/users/reset-password`
// export const API_CHECKOUT = `${API_URL}/checkout/now`
// export const API_CHECKOUT_ITEM = `${API_URL}/checkout/items`
export const API_CHECKOUT = `http://127.0.0.1:5100/api/v1/checkout/now`
export const API_CHECKOUT_ITEM = `http://127.0.0.1:5100/api/v1/checkout/items`
export const API_CARTS = `${API_URL}/carts`