import { useState } from "react";

const ListingForm: React.FC = () => {
  const [images, setImages] = useState<File[]>([]);
  const [productDetails, setProductDetails] = useState({
    name: "",
    price: "",
    quantity: 1,
    category: "Toys",
    description: "",
    warranty: "",
    enablePromo: "No",
    discount: "",
    startDate: "",
    endDate: "",
  });
  const [termsChecked, setTermsChecked] = useState(false);
  const [declarationChecked, setDeclarationChecked] = useState(false);
  const [loading, setLoading] = useState(false);

  const handleImageUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files && event.target.files[0]) {
      if (images.length < 4) {
        setImages([...images, event.target.files[0]]);
      } else {
        alert("You can only upload a maximum of 4 pictures.");
      }
    }
  };

  const handleImageRemove = (index: number) => {
    const confirmation = confirm("Are you sure you want to delete this image?");
    if (confirmation) {
      setImages((prev) => prev.filter((_, i) => i !== index));
    }
  };

  const handlePromptUpload = () => {
    const input = document.getElementById("imageInput") as HTMLInputElement;
    input?.click();
  };

  const handleQuantityChange = (amount: number) => {
    setProductDetails((prev) => ({
      ...prev,
      quantity: Math.max(1, prev.quantity + amount),
    }));
  };

  const handleInputChange = (field: string, value: string) => {
    setProductDetails((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  const handleSubmit = async () => {
    const { name, price, category, description, warranty } =
      productDetails;

    if (
      !name ||
      !price ||
      !category ||
      !description ||
      !warranty ||
      !termsChecked ||
      !declarationChecked
    ) {
      alert("Please fill all required fields and check all required boxes.");
      return;
    }

    if (
      productDetails.enablePromo === "Yes" &&
      (!productDetails.discount || !productDetails.startDate || !productDetails.endDate)
    ) {
      alert("Please complete all promo fields.");
      return;
    }

    try {
      setLoading(true);
      // Upload main image
      const imageUrl = images[0] ? await uploadImage(images[0]) : null;

      // Prepare product payload
      const productPayload = {
        category: productDetails.category,
        descriptions: productDetails.description,
        id: 0, // placeholder ID, will be generated by the backend
        image_url: imageUrl,
        is_warranty: productDetails.warranty === "Yes",
        name: productDetails.name,
        price: Number(productDetails.price),
        stock: productDetails.quantity,
        user_id: 1, // placeholder
      };

      // Send product to Products API
      const productResponse = await fetch(
        "https://api.babycycle.my.id/api/v1/products",
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(productPayload),
        }
      );

      if (!productResponse.ok) {
        throw new Error("Failed to submit product. Please try again.");
      }

      const productData = await productResponse.json();

      // If promo is enabled, send discount details
      if (productDetails.enablePromo === "Yes") {
        const discountPayload = {
          product_id: productData.id, // ID from the product response
          discount_percentage: productDetails.discount,
          start_date: productDetails.startDate,
          end_date: productDetails.endDate,
          is_active: true,
        };

        const discountResponse = await fetch(
          "https://api.babycycle.my.id/api/v1/discounts",
          {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
            },
            body: JSON.stringify(discountPayload),
          }
        );

        if (!discountResponse.ok) {
          throw new Error("Failed to submit discount details.");
        }
      }

      alert("Product submitted successfully!");
      resetForm();
    } catch (error) {
      console.error("Error:", error);
      alert("Failed to submit product.");
    } finally {
      setLoading(false);
    }
  };

  const uploadImage = async (file: File): Promise<string | null> => {
    const formData = new FormData();
    formData.append("image", file);

    try {
      const response = await fetch("https://api.babycycle.my.id/api/v1/products/upload", {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        throw new Error("Failed to upload image");
      }

      const data = await response.json();
      return data.image_url; // Assuming the API returns the image URL
    } catch (error) {
      console.error("Image upload error:", error);
      return null;
    }
  };

  const resetForm = () => {
    setProductDetails({
      name: "",
      price: "",
      quantity: 1,
      category: "Toys",
      description: "",
      warranty: "",
      enablePromo: "No",
      discount: "",
      startDate: "",
      endDate: "",
    });
    setImages([]);
    setTermsChecked(false);
    setDeclarationChecked(false);
  };
  return (
    <div className="p-8 mt-10 bg-white min-h-screen max-w-[1440px]">
      <h2 className="text-heading-xl font-bold mb-8">What are you listing today?</h2>
      <div className="flex space-x-8">

        {/* Left Side - Picture Upload */}
        <div className="flex flex-col space-y-4">
          {/* Main Image */}
          <div
            className="bg-gray-300 relative w-[500px] h-[500px] flex justify-center items-center cursor-pointer hover:bg-gray-400 rounded-lg"
            onClick={handlePromptUpload}
          >
            {images[0] ? (
              <div className="relative w-full h-full">
                <img
                  src={URL.createObjectURL(images[0])}
                  alt="Uploaded"
                  className="w-full h-full object-cover rounded-lg"
                />
                <button
                  className="absolute bottom-2 right-2 bg-red-500 text-white p-1 rounded-full hover:bg-red-600"
                  onClick={(e) => {
                    e.stopPropagation();
                    handleImageRemove(0);
                  }}
                >
                  <img
                    src="/assets/remove.png"
                    alt="Remove"
                    className="w-6 h-6"
                  />
                </button>
              </div>
            ) : (
              <p className="text-gray-500 text-lg">Select photos</p>
            )}
          </div>

          {/* Thumbnails */}
          <div className="flex space-x-4 w-[500px]">
            {[...Array(3)].map((_, index) => (
              <div
                key={index}
                className="bg-gray-300 relative w-[150px] h-[150px] flex justify-center items-center cursor-pointer hover:bg-gray-400 rounded-lg"
                onClick={handlePromptUpload}
              >
                {images[index + 1] ? (
                  <div className="relative w-full h-full">
                    <img
                      src={URL.createObjectURL(images[index + 1])}
                      alt="Uploaded"
                      className="w-full h-full object-cover rounded-lg"
                    />
                    <button
                      className="absolute bottom-2 right-2 bg-red-500 text-white p-1 rounded-full hover:bg-red-600"
                      onClick={(e) => {
                        e.stopPropagation();
                        handleImageRemove(index + 1);
                      }}
                    >
                      <img
                        src="/assets/remove.png"
                        alt="Remove"
                        className="w-4 h-4"
                      />
                    </button>
                  </div>
                ) : (
                  <p className="text-gray-500 text-sm">+</p>
                )}
              </div>
            ))}
          </div>
          <input
            type="file"
            id="imageInput"
            accept="image/*"
            onChange={handleImageUpload}
            className="hidden"
          />
        </div>

        {/* Right Side - Form */}
        <div className="p-6 border border-textBlue rounded-lg" style={{ width: "720px" }}>
          <h3 className="text-heading-xl font-bold mb-6">Product Details</h3>
          <div className="space-y-4">
            {/* Product Name */}
            <div className="flex items-center">
              <label className="w-1/4 text-textBlue">Product name</label>
              <input
                type="text"
                value={productDetails.name}
                onChange={(e) => handleInputChange("name", e.target.value)}
                className="flex-1 border border-gray-300 rounded-md px-2 py-1"
              />
            </div>

            {/* Price */}
            <div className="flex items-center">
              <label className="w-1/4 text-textBlue">Price (IDR)</label>
              <input
                type="number"
                value={productDetails.price}
                onChange={(e) => handleInputChange("price", e.target.value)}
                className="flex-1 border border-gray-300 rounded-md px-2 py-1"
              />
            </div>

            {/* Quantity */}
            <div className="flex items-center">
              <label className="w-1/4 text-textBlue">Quantity</label>
              <div className="flex items-center space-x-2">
                <button
                  onClick={() => handleQuantityChange(-1)}
                  className="bg-black text-white px-3 py-1 rounded-md"
                >
                  -
                </button>
                <span>{productDetails.quantity}</span>
                <button
                  onClick={() => handleQuantityChange(1)}
                  className="bg-black text-white px-3 py-1 rounded-md"
                >
                  +
                </button>
              </div>
            </div>

            {/* Category */}
            <div className="flex items-center">
              <label className="w-1/4 text-textBlue">Category</label>
              <select
                value={productDetails.category}
                onChange={(e) => handleInputChange("category", e.target.value)}
                className="flex-1 border border-gray-300 rounded-md px-2 py-1"
              >
                <option value="Toys">Toys</option>
                <option value="Stroller">Stroller</option>
                <option value="Carrier">Carrier</option>
                <option value="Furniture">Furniture</option>
                <option value="Others">Others</option>
              </select>
            </div>

            {/* Description */}
            <div className="flex items-center">
              <label className="w-1/4 text-textBlue">Description</label>
              <textarea
                value={productDetails.description}
                onChange={(e) => handleInputChange("description", e.target.value)}
                className="flex-1 border border-gray-300 rounded-md px-2 py-1"
              ></textarea>
            </div>

            {/* Warranty */}
            <div className="flex items-center">
              <label className="w-1/4 text-textBlue">Warranty</label>
              <div className="flex space-x-4">
                <label>
                  <input
                    type="radio"
                    value="Yes"
                    checked={productDetails.warranty === "Yes"}
                    onChange={(e) => handleInputChange("warranty", e.target.value)}
                  />{" "}
                  Yes
                </label>
                <label>
                  <input
                    type="radio"
                    value="No"
                    checked={productDetails.warranty === "No"}
                    onChange={(e) => handleInputChange("warranty", e.target.value)}
                  />{" "}
                  No
                </label>
              </div>
            </div>

            <hr className="border-t-2 border-textBlue my-4" />

            {/* Enable Promo */}
            <div className="flex items-center">
              <label className="w-1/4 text-textBlue">Enable Promo?</label>
              <div className="flex space-x-4">
                <label>
                  <input
                    type="radio"
                    value="Yes"
                    checked={productDetails.enablePromo === "Yes"}
                    onChange={(e) => handleInputChange("enablePromo", e.target.value)}
                  />{" "}
                  Yes
                </label>
                <label>
                  <input
                    type="radio"
                    value="No"
                    checked={productDetails.enablePromo === "No"}
                    onChange={(e) => handleInputChange("enablePromo", e.target.value)}
                  />{" "}
                  No
                </label>
              </div>
            </div>

            {/* Discount */}
            <div className="flex items-center">
              <label className="w-1/4 text-textBlue">Discount (%)</label>
              <input
                type="number"
                value={productDetails.discount}
                onChange={(e) => handleInputChange("discount", e.target.value)}
                disabled={productDetails.enablePromo === "No"}
                className="flex-1 border border-gray-300 rounded-md px-2 py-1"
              />
            </div>

            {/* Start Date */}
            <div className="flex items-center">
              <label className="w-1/4 text-textBlue">Start Date</label>
              <input
                type="date"
                value={productDetails.startDate}
                onChange={(e) => handleInputChange("startDate", e.target.value)}
                disabled={productDetails.enablePromo === "No"}
                className="flex-1 border border-gray-300 rounded-md px-2 py-1"
              />
            </div>

            {/* End Date */}
            <div className="flex items-center">
              <label className="w-1/4 text-textBlue">End Date</label>
              <input
                type="date"
                value={productDetails.endDate}
                onChange={(e) => handleInputChange("endDate", e.target.value)}
                disabled={productDetails.enablePromo === "No"}
                className="flex-1 border border-gray-300 rounded-md px-2 py-1"
              />
            </div>

            {/* Terms */}
            <div className="flex items-center">
              <input
                type="checkbox"
                checked={termsChecked}
                onChange={(e) => setTermsChecked(e.target.checked)}
                className="mr-2"
              />
              <label>
                I have read the{" "}
                <a href="#" className="text-textBlue">
                  Terms and Agreements policy
                </a>
              </label>
            </div>

            {/* Declaration */}
            <div className="flex items-center">
              <input
                type="checkbox"
                checked={declarationChecked}
                onChange={(e) => setDeclarationChecked(e.target.checked)}
                className="mr-2"
              />
              <label>
                I hereby declare that all information provided is accurate and
                valid.
              </label>
            </div>
          </div>


export default ListingForm;

          {/* Submit Button */}
          <div className="flex justify-center mt-6">
            <button
              onClick={handleSubmit}
              className="bg-textBlue text-white px-6 py-2 rounded-md"
              disabled={loading}
            >
              {loading ? "Submitting..." : "Submit"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ListingForm;